### PR TITLE
Corrected example code

### PR DESCRIPTION
**Pull request by davidemorotti**

### CODE REVIEW

**Comment by pichfl** [comment]
Thanks a lot for this!

**Comment by davidemorotti** [comment]
You're welcome! Thanks for the package!

**Comment by davidemorotti** [comment]
Please note also that on newer versions of Electron, the function ’loadUrl()’ has been renamed into ’loadURL()’.

Don‘t know if you want to change this as well.

**Comment by pichfl** [comment]
I haven't worked on an Electron project in quite some time so it's hard to keep track. Feel free to send a second PR.

**Pull request merged**
